// <auto-generated />
namespace LexiconLMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mer2308 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mer2308));
        
        string IMigrationMetadata.Id
        {
            get { return "201708230707120_mer2308"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
