// <auto-generated />
namespace LexiconLMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ErrorStudentType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ErrorStudentType));
        
        string IMigrationMetadata.Id
        {
            get { return "201708080835483_Error-Student-Type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
